"""initial schema

Revision ID: 235bd3e11258
Revises:
Create Date: 2026-08-18 17:10:30.740076
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "235bd3e11258"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "schools",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schools")),
    )
    op.create_index(op.f("ix_schools_code"), "schools", ["code"], unique=True)
    op.create_table(
        "classrooms",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("school_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("academic_year", sa.Integer(), nullable=False),
        sa.Column("shift", sa.String(length=16), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "shift IN ('Manhã', 'Tarde', 'Noite')", name=op.f("ck_classrooms_valid_shift")
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_classrooms_school_id_schools"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_classrooms")),
        sa.UniqueConstraint(
            "school_id", "academic_year", "name", "shift", name="uq_classrooms_identity"
        ),
    )
    op.create_index(op.f("ix_classrooms_school_id"), "classrooms", ["school_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("school_id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("full_name", sa.String(length=160), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=24), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('admin', 'coordinator', 'viewer')", name=op.f("ck_users_valid_role")
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_users_school_id_schools"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("school_id", "email", name="uq_users_school_email"),
    )
    op.create_index(op.f("ix_users_school_id"), "users", ["school_id"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("school_id", sa.Uuid(), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "details",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_logs_actor_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_audit_logs_school_id_schools"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(
        op.f("ix_audit_logs_actor_user_id"), "audit_logs", ["actor_user_id"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_school_id"), "audit_logs", ["school_id"], unique=False)
    op.create_index(
        "ix_audit_logs_school_occurred_at", "audit_logs", ["school_id", "occurred_at"], unique=False
    )
    op.create_table(
        "students",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("school_id", sa.Uuid(), nullable=False),
        sa.Column("classroom_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("preferred_name", sa.String(length=100), nullable=True),
        sa.Column("enrollment_code", sa.String(length=60), nullable=False),
        sa.Column("search_text", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="active", nullable=False),
        sa.Column(
            "face_enrollment_status",
            sa.String(length=24),
            server_default="not_enrolled",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "face_enrollment_status IN ('not_enrolled', 'enrolled', 'review_needed')",
            name=op.f("ck_students_valid_face_status"),
        ),
        sa.CheckConstraint(
            "status IN ('active', 'inactive')", name=op.f("ck_students_valid_status")
        ),
        sa.ForeignKeyConstraint(
            ["classroom_id"],
            ["classrooms.id"],
            name=op.f("fk_students_classroom_id_classrooms"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_students_school_id_schools"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_students")),
        sa.UniqueConstraint("school_id", "enrollment_code", name="uq_students_enrollment"),
    )
    op.create_index(op.f("ix_students_classroom_id"), "students", ["classroom_id"], unique=False)
    op.create_index(op.f("ix_students_school_id"), "students", ["school_id"], unique=False)
    op.create_index(
        "ix_students_school_search_text", "students", ["school_id", "search_text"], unique=False
    )
    op.create_table(
        "occurrences",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("school_id", sa.Uuid(), nullable=False),
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("responsible_name", sa.String(length=160), nullable=True),
        sa.Column("participants", sa.Text(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column("identification_source", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="active", nullable=False),
        sa.CheckConstraint(
            "identification_source IN ('manual', 'facial')",
            name=op.f("ck_occurrences_valid_identification_source"),
        ),
        sa.CheckConstraint(
            "status IN ('active', 'cancelled')", name=op.f("ck_occurrences_valid_status")
        ),
        sa.CheckConstraint(
            "type IN ('late_arrival', 'early_departure', 'school_record', "
            "'meeting_minutes', 'warning')",
            name=op.f("ck_occurrences_valid_type"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_occurrences_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_occurrences_school_id_schools"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("fk_occurrences_student_id_students"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_occurrences")),
    )
    op.create_index(
        op.f("ix_occurrences_created_by_id"), "occurrences", ["created_by_id"], unique=False
    )
    op.create_index(op.f("ix_occurrences_school_id"), "occurrences", ["school_id"], unique=False)
    op.create_index(op.f("ix_occurrences_student_id"), "occurrences", ["student_id"], unique=False)
    op.create_index(
        "ix_occurrences_student_occurred_at",
        "occurrences",
        ["student_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "attachments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("school_id", sa.Uuid(), nullable=False),
        sa.Column("occurrence_id", sa.Uuid(), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("original_name", sa.String(length=255), nullable=False),
        sa.Column("media_type", sa.String(length=120), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["occurrence_id"],
            ["occurrences.id"],
            name=op.f("fk_attachments_occurrence_id_occurrences"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_attachments_school_id_schools"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attachments")),
    )
    op.create_index(
        op.f("ix_attachments_occurrence_id"), "attachments", ["occurrence_id"], unique=True
    )
    op.create_index(op.f("ix_attachments_school_id"), "attachments", ["school_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_attachments_school_id"), table_name="attachments")
    op.drop_index(op.f("ix_attachments_occurrence_id"), table_name="attachments")
    op.drop_table("attachments")
    op.drop_index("ix_occurrences_student_occurred_at", table_name="occurrences")
    op.drop_index(op.f("ix_occurrences_student_id"), table_name="occurrences")
    op.drop_index(op.f("ix_occurrences_school_id"), table_name="occurrences")
    op.drop_index(op.f("ix_occurrences_created_by_id"), table_name="occurrences")
    op.drop_table("occurrences")
    op.drop_index("ix_students_school_search_text", table_name="students")
    op.drop_index(op.f("ix_students_school_id"), table_name="students")
    op.drop_index(op.f("ix_students_classroom_id"), table_name="students")
    op.drop_table("students")
    op.drop_index("ix_audit_logs_school_occurred_at", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_school_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_user_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_users_school_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_classrooms_school_id"), table_name="classrooms")
    op.drop_table("classrooms")
    op.drop_index(op.f("ix_schools_code"), table_name="schools")
    op.drop_table("schools")
    # ### end Alembic commands ###
