"""store facial enrollment pose

Revision ID: 36474562c574
Revises: c2fad63b17ef
Create Date: 2026-08-18 18:31:00.130524
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "36474562c574"
down_revision: str | None = "c2fad63b17ef"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "face_embeddings", sa.Column("enrollment_pose", sa.String(length=16), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("face_embeddings", "enrollment_pose")
    # ### end Alembic commands ###
