"""add face embeddings

Revision ID: c2fad63b17ef
Revises: 235bd3e11258
Create Date: 2026-08-18 17:38:29.292008
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "c2fad63b17ef"
down_revision: str | None = "235bd3e11258"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "face_embeddings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("school_id", sa.Uuid(), nullable=False),
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("embedding", postgresql.ARRAY(sa.Float()), nullable=False),
        sa.Column("quality_score", sa.Float(), nullable=False),
        sa.Column("model_version", sa.String(length=80), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quality_score >= 0 AND quality_score <= 1",
            name=op.f("ck_face_embeddings_valid_quality"),
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_face_embeddings_school_id_schools"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("fk_face_embeddings_student_id_students"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_face_embeddings")),
    )
    op.create_index(
        op.f("ix_face_embeddings_school_id"), "face_embeddings", ["school_id"], unique=False
    )
    op.create_index(
        "ix_face_embeddings_school_student",
        "face_embeddings",
        ["school_id", "student_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_face_embeddings_student_id"), "face_embeddings", ["student_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_face_embeddings_student_id"), table_name="face_embeddings")
    op.drop_index("ix_face_embeddings_school_student", table_name="face_embeddings")
    op.drop_index(op.f("ix_face_embeddings_school_id"), table_name="face_embeddings")
    op.drop_table("face_embeddings")
    # ### end Alembic commands ###
